[package]
name = "chipioindustries/smartselect"
description = "Roblox plugin for selecting objects based on given criteria"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["wally.exe", "aftman", "*.zip"]

[dependencies]
t = "osyrisrblx/t@3.0.0"

[dev-dependencies]
Roact = "roblox/roact@1.4.2"
RoactHooks = "kampfkarren/roact-hooks@0.4.1"
TestEZ = "roblox/testez@0.4.1"